### ISSUE TITLE
code: mne-rsa

### ISSUE THREAD

**Issue by wmvanvliet** [ResearchSoftwareHour/rsh-notes#13]
Last time the topic of how to package software came up. A very big part of getting others to actually use your software, hence cite it and give you everlasting glory, is to provide documentation for it. But writing documentation takes a lot of effort. 

I'd like to offer up the repository for the MNE-RSA project (https://github.com/wmvanvliet/mne-rsa/) and its auto-generated companion website (https://users.aalto.fi/~vanvlm1/mne-rsa) as an example of how to get the most "bang for your buck" regarding documentation:

 1. API docs rendered from your Python docstrings (https://users.aalto.fi/~vanvlm1/mne-rsa/api.html)
 2. Examples rendered from python scripts you drop into the `examples` folder (https://users.aalto.fi/~vanvlm1/mne-rsa/auto_examples/index.html)

Together, the API docs and examples provide a good bare minimum of what documentation you need for others to use your software. With the proper tools, this can be obtained with relatively little effort.

A template for setting all this up is available here: https://github.com/mne-tools/mne-project-template

**Comment by bast** [comment]
Thanks for submitting it! This is a great example: here we will all learn something new, including me.

**Comment by bast** [comment]
Tuesdays somehow arrive quicker than expected but perhaps we can discuss this in the May 19 stream?

**Comment by wmvanvliet** [comment]
Is there anything you need from me? Some explanation of some things?

**Comment by bast** [comment]
Sorry for being slow but this could fit nicely into tomorrow where I want to discuss a bit the documentation. This is a very nice example and if you are OK with it, I can browse it a bit and comment. I will look a bit more so that I understand better how it works but I like it a lot.

**Comment by wmvanvliet** [comment]
Cool!

I've now setup a GitHub action for building the docs, producing them as an artifact for download :)

**Comment by bast** [comment]
Thanks for the changes! Really nice project that demonstrates a couple of very interesting tools.

**Comment by bast** [comment]
Having browsed a bit more: great example and great setup. I didn't know https://sphinx-gallery.github.io/ until now.

The only constructive suggestion for improvement I might give if I have time is that version information is in 3 places and I will maybe suggest how to track that only in one place and have both setup.py and conf.py infer it. But it is a minor point and please don't fix it yet :-)

**Comment by wmvanvliet** [comment]
good point!

**Comment by bast** [comment]
Discussed in https://researchsoftwarehour.github.io/sessions/rsh-004/.
