### ISSUE TITLE
xargs can run on multiple cores

### ISSUE THREAD

**Issue by bast** [ResearchSoftwareHour/rsh-notes#38]
This can speed up when running the same script on many files.

**Comment by ashwinvis** [comment]
-P max-procs, --max-procs=max-procs
              Run up to max-procs processes at a time; 

Nice, TIL.

There is also Perl based [GNU parallel](https://www.gnu.org/software/parallel/) with a more expressive syntax. Here is an example that I just used
```sh
find -name *.tar | parallel 'zstdmt {} -o {.}_01.tar.zst'
./abl_neutral_6x20x6_V1280.x1500.x1280._2020-06-03_07-27-18/data/abl_neutral_6x20x6_V1280.x1500.x1280._2020-06-03_07-27-18.tar : 43.09%   (6607264768 => 2846758592 bytes, ./abl_neutral_6x20x6_V1280.x1500.x1280._2020-06-03_07-27-18/data/abl_neutral_6x20x6_V1280.x1500.x1280._2020-06-03_07-27-18_01.tar.zst) 
./abl_neutral_12x24x12_V1280.x1500.x1280._2020-06-04_02-31-20/data/abl_neutral_12x24x12_V1280.x1500.x1280._2020-06-04_02-31-20.tar : 42.50%   (8782504960 => 3732330465 bytes, ./abl_neutral_12x24x12_V1280.x1500.x1280._2020-06-04_02-31-20/data/abl_neutral_12x24x12_V1280.x1500.x1280._2020-06-04_02-31-20_01.tar.zst)
```

It also has an interesting / peculiar way of enforcing [citations](https://www.gnu.org/software/parallel/parallel_design.html#Citation-notice).

**Comment by bast** [comment]
Interesting! Thanks! Both the tool and the citation solution.

**Comment by bast** [comment]
Going to demo this tomorrow: https://github.com/ResearchSoftwareHour/demo-parallel-tasks

**Comment by bast** [comment]
Discussed in https://researchsoftwarehour.github.io/sessions/rsh-008/.
